CFLAGS = -g -Wall

all:	ex_getopt ex_getopt_long

ex_getopt_long:	ex_getopt_long.c
		gcc $(CFLAGS) -o ex_getopt_long ex_getopt_long.c

ex_getopt:	ex_getopt.c
		gcc $(CFLAGS) -o ex_getopt ex_getopt.c

